# Generated by Django 5.2.6 on 2025-11-23 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_painel', models.DateField(verbose_name='Data do Painel')),
                ('horario_inicial_painel', models.TimeField(verbose_name='Horário Inicial')),
                ('horario_final_painel', models.TimeField(verbose_name='Horário Final')),
                ('numero_de_user', models.PositiveIntegerField(verbose_name='Capacidade de Alunos')),
                ('data_create_painel', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_at_painel', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aulas', models.ManyToManyField(related_name='paineis', to='aulas.aulas', verbose_name='Aulas/Exercícios')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador (Professor/Admin)')),
            ],
            options={
                'verbose_name': 'Painel de Agendamento',
                'verbose_name_plural': 'Painéis de Agendamento',
                'ordering': ['-data_painel', 'horario_inicial_painel'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Agendamento')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluído')], default='Agendado', max_length=20, verbose_name='Status')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_agendamentos', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamento.painel', verbose_name='Painel')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('painel', 'aluno')},
            },
        ),
    ]
