# Generated by Django 5.2.6 on 2025-11-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painel',
            name='numero_de_user',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe em branco para sem limite', null=True, verbose_name='Capacidade de Alunos'),
        ),
    ]
