# Generated by Django 5.2.6 on 2025-11-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_painel_numero_de_user'),
        ('painel', '0003_painel_numero_de_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='painel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='painel.painel', verbose_name='Painel'),
        ),
        migrations.DeleteModel(
            name='Painel',
        ),
    ]
