# Generated by Django 5.2.8 on 2026-09-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_agendamento_arquivado_em_agendamento_rede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Faltou', 'Faltou (aluno ausente)'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluído')], default='Agendado', max_length=20, verbose_name='Status'),
        ),
    ]
