# Generated by Django 5.2.8 on 2026-09-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0004_painel_arquivado_em_painel_rede_painel_unidade_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaDeNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('nenhum', 'Nao quero receber')], default='whatsapp', max_length=10, verbose_name='canal')),
                ('avisar_vencimento', models.BooleanField(default=True, verbose_name='avisar sobre vencimento')),
                ('avisar_aula', models.BooleanField(default=True, verbose_name='avisar na vespera da aula')),
                ('avisar_aniversario', models.BooleanField(default=False, verbose_name='avisar aniversario')),
                ('receber_novidades', models.BooleanField(default=False, verbose_name='receber novidades da academia')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'preferencia de notificacao',
                'verbose_name_plural': 'preferencias de notificacao',
            },
        ),
        migrations.CreateModel(
            name='ListaDeEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avisado', models.BooleanField(default=False, verbose_name='avisado sobre a vaga')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to='usuarios.usuario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_espera', to='painel.painel')),
            ],
            options={
                'verbose_name': 'entrada na lista de espera',
                'verbose_name_plural': 'entradas na lista de espera',
                'ordering': ['criado_em'],
                'constraints': [models.UniqueConstraint(fields=('turma', 'aluno'), name='espera_unica_por_aluno_e_turma')],
            },
        ),
    ]
