"""Mapa dos modulos do painel para as rotas (usado pelo menu e pelos testes)."""

from gestao.permissoes import Modulo

ROTAS: dict[str, str] = {
    Modulo.VISAO_GERAL: "gestao:visao_geral",
    Modulo.ALUNOS: "gestao:alunos",
    Modulo.PROFESSORES: "gestao:professores",
    Modulo.AULAS: "gestao:aulas",
    Modulo.AGENDA: "gestao:agenda",
    Modulo.FINANCEIRO: "gestao:financeiro",
    Modulo.RELATORIOS: "gestao:relatorios",
    Modulo.COMUNICACAO: "gestao:comunicacao",
    Modulo.IDENTIDADE: "gestao:identidade",
    Modulo.EQUIPE: "gestao:equipe",
    Modulo.PLANO: "gestao:plano",
    Modulo.PRIVACIDADE: "gestao:privacidade",
    Modulo.DOMINIO: "gestao:dominio",
    Modulo.REDE: "rede:painel",
    Modulo.UNIDADES: "rede:unidades",
    Modulo.REPASSES: "rede:repasses",
    Modulo.GOVERNANCA: "rede:governanca",
    Modulo.COMUNICADOS: "rede:comunicados",
    Modulo.APROVACOES: "rede:aprovacoes",
    Modulo.CATALOGO: "rede:catalogo",
    Modulo.AUDITORIA: "gestao:auditoria",
    Modulo.CRM: "relacionamento:funil",
    Modulo.RETENCAO: "relacionamento:retencao",
    Modulo.ACESSO: "acesso:painel",
    Modulo.COBRANCA: "cobranca:painel",
    Modulo.PARCEIROS: "acesso:parceiros",
    Modulo.COMISSOES: "remuneracao:regras",
    Modulo.GAMIFICACAO: "gamificacao:regras",
    Modulo.PESQUISAS: "nps:pesquisas",
}
