# Generated by Django 5.2.8 on 2026-09-13 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoDeSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('categoria', models.CharField(choices=[('duvida', 'Duvida de uso'), ('financeiro', 'Financeiro'), ('tecnico', 'Problema tecnico'), ('estrutura', 'Estrutura ou equipamento'), ('sugestao', 'Sugestao')], default='duvida', max_length=12, verbose_name='categoria')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=8, verbose_name='prioridade')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando o solicitante'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=15, verbose_name='situacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='resolvido em')),
                ('aberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='usuarios.usuario', verbose_name='aluno')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.rede')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='core.unidade')),
            ],
            options={
                'verbose_name': 'chamado de suporte',
                'verbose_name_plural': 'chamados de suporte',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemDoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto')),
                ('interna', models.BooleanField(default=False, verbose_name='nota interna (nao aparece para o solicitante)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_de_chamado', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conta.chamadodesuporte')),
            ],
            options={
                'verbose_name': 'mensagem do chamado',
                'verbose_name_plural': 'mensagens do chamado',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='chamadodesuporte',
            index=models.Index(fields=['rede', 'situacao'], name='conta_chama_rede_id_2b5a47_idx'),
        ),
    ]
