# Generated by Django 5.2.8 on 2026-09-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0005_aulas_arquivado_em_aulas_rede_aulas_unidade_and_more'),
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoDeMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='nome do arquivo')),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('imagem', 'Imagem'), ('audio', 'Audio'), ('documento', 'Documento')], default='video', max_length=12, verbose_name='tipo')),
                ('situacao', models.CharField(choices=[('enviando', 'Enviando'), ('processando', 'Processando'), ('pronto', 'Pronto'), ('erro', 'Erro'), ('removido', 'Removido')], default='enviando', max_length=12, verbose_name='situacao')),
                ('mime', models.CharField(blank=True, max_length=120, verbose_name='tipo de conteudo')),
                ('tamanho_previsto', models.BigIntegerField(default=0, verbose_name='tamanho previsto (bytes)')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='tamanho gravado (bytes)')),
                ('hash_esperado', models.CharField(blank=True, max_length=64, verbose_name='hash esperado (sha256)')),
                ('hash_final', models.CharField(blank=True, max_length=64, verbose_name='hash do arquivo (sha256)')),
                ('largura', models.PositiveIntegerField(blank=True, null=True, verbose_name='largura (px)')),
                ('altura', models.PositiveIntegerField(blank=True, null=True, verbose_name='altura (px)')),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True, verbose_name='duracao (s)')),
                ('caminho', models.CharField(blank=True, max_length=300, verbose_name='caminho no armazenamento')),
                ('publicado', models.BooleanField(default=False, verbose_name='visivel para o aluno')),
                ('erro', models.CharField(blank=True, max_length=300, verbose_name='ultimo erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='concluido em')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_enviadas', to='aulas.aulas')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias', to='core.unidade')),
            ],
            options={
                'verbose_name': 'arquivo de midia',
                'verbose_name_plural': 'arquivos de midia',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParteDeMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='numero da parte')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('hash_da_parte', models.CharField(blank=True, max_length=64, verbose_name='hash da parte (sha256)')),
                ('recebida_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='midia.arquivodemidia')),
            ],
            options={
                'verbose_name': 'parte de envio',
                'verbose_name_plural': 'partes de envio',
                'ordering': ['numero'],
            },
        ),
        migrations.AddIndex(
            model_name='arquivodemidia',
            index=models.Index(fields=['rede', 'situacao'], name='midia_arqui_rede_id_7759fc_idx'),
        ),
        migrations.AddIndex(
            model_name='arquivodemidia',
            index=models.Index(fields=['rede', 'tipo'], name='midia_arqui_rede_id_05d8b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='partedemidia',
            constraint=models.UniqueConstraint(fields=('arquivo', 'numero'), name='midia_parte_unica'),
        ),
    ]
