services:
  web:
    build: .
    container_name: academia_web
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    build: ./nginx
    container_name: academia_nginx
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "127.0.0.1:8002:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
