# Generated by Django 5.2.8 on 2026-09-13 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsavel')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('dominio', models.CharField(blank=True, max_length=253, verbose_name='dominio proprio')),
                ('status', models.CharField(choices=[('trial', 'Em teste'), ('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('somente_leitura', 'Somente leitura'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20, verbose_name='status')),
                ('trial_termina_em', models.DateTimeField(blank=True, null=True, verbose_name='teste termina em')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='observacoes internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'rede',
                'verbose_name_plural': 'redes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='codigo')),
                ('tipo', models.CharField(choices=[('propria', 'Propria'), ('franqueada', 'Franqueada'), ('licenciada', 'Licenciada')], default='propria', max_length=20, verbose_name='tipo')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereco')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('em_implantacao', 'Em implantacao')], default='ativa', max_length=20, verbose_name='status')),
                ('sobrescrever_branding', models.BooleanField(default=False, verbose_name='pode sobrescrever a marca')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_geridas', to=settings.AUTH_USER_MODEL, verbose_name='gestor responsavel')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.rede')),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['rede', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('superadmin_plataforma', 'Superadmin da plataforma'), ('admin_rede', 'Administrador da rede'), ('gestor_unidade', 'Gestor de unidade'), ('recepcao', 'Recepcao'), ('professor', 'Professor'), ('financeiro_rede', 'Financeiro da rede'), ('auditor_rede', 'Auditor da rede'), ('aluno', 'Aluno')], max_length=30, verbose_name='papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vinculo de usuario',
                'verbose_name_plural': 'vinculos de usuario',
                'ordering': ['rede', 'usuario'],
            },
        ),
        migrations.AddConstraint(
            model_name='unidade',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('rede', 'codigo'), name='unidade_codigo_unico_por_rede'),
        ),
        migrations.AddConstraint(
            model_name='vinculousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'rede', 'unidade', 'papel'), name='vinculo_unico_por_usuario_rede_unidade_papel'),
        ),
    ]
