# Generated by Django 5.2.8 on 2026-09-13 14:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('papel', models.CharField(choices=[('superadmin_plataforma', 'Superadmin da plataforma'), ('admin_rede', 'Administrador da rede'), ('gestor_unidade', 'Gestor de unidade'), ('recepcao', 'Recepcao'), ('professor', 'Professor'), ('financeiro_rede', 'Financeiro da rede'), ('auditor_rede', 'Auditor da rede'), ('aluno', 'Aluno')], max_length=32, verbose_name='papel')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=16)),
                ('expira_em', models.DateTimeField(verbose_name='expira em')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('aceito_em', models.DateTimeField(blank=True, null=True)),
                ('aceito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to=settings.AUTH_USER_MODEL, verbose_name='aceito por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.rede', verbose_name='rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'convite de equipe',
                'verbose_name_plural': 'convites de equipe',
                'ordering': ('-criado_em',),
            },
        ),
    ]
