# Generated by Django 5.2.8 on 2026-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conviteequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='certificado_emitido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='certificado emitido em'),
        ),
        migrations.AddField(
            model_name='rede',
            name='certificado_erro',
            field=models.TextField(blank=True, verbose_name='erro do certificado'),
        ),
        migrations.AddField(
            model_name='rede',
            name='certificado_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('emitindo', 'Emitindo'), ('emitido', 'Emitido'), ('erro', 'Com erro')], default='pendente', max_length=20, verbose_name='status do certificado'),
        ),
        migrations.AddField(
            model_name='rede',
            name='dominio_diagnostico',
            field=models.CharField(blank=True, max_length=250, verbose_name='diagnostico do dominio'),
        ),
        migrations.AddField(
            model_name='rede',
            name='dominio_status',
            field=models.CharField(choices=[('nao_configurado', 'Sem dominio proprio'), ('pendente_dns', 'Aguardando DNS'), ('verificando', 'Verificando'), ('pronto', 'Pronto'), ('erro', 'Com erro')], default='nao_configurado', max_length=20, verbose_name='status do dominio'),
        ),
        migrations.AddField(
            model_name='rede',
            name='dominio_tentativas',
            field=models.PositiveIntegerField(default=0, verbose_name='tentativas de verificacao'),
        ),
        migrations.AddField(
            model_name='rede',
            name='dominio_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='token de verificacao'),
        ),
        migrations.AddField(
            model_name='rede',
            name='dominio_verificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dominio verificado em'),
        ),
        migrations.AddField(
            model_name='rede',
            name='media_prefixo',
            field=models.CharField(blank=True, help_text='Namespace dos arquivos deste cliente (padrao: o slug).', max_length=80, verbose_name='prefixo da midia'),
        ),
    ]
