# Generated by Django 5.2.8 on 2026-09-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='titulo')),
                ('pergunta', models.CharField(max_length=300, verbose_name='pergunta')),
                ('tipo', models.CharField(choices=[('nps', 'NPS (0 a 10)'), ('nota', 'Nota (1 a 5)'), ('texto', 'Texto livre')], default='nps', max_length=8, verbose_name='tipo')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'pesquisa',
                'verbose_name_plural': 'pesquisas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nota')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario')),
                ('tratada_em', models.DateTimeField(blank=True, null=True, verbose_name='tratada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_de_pesquisa', to='usuarios.usuario', verbose_name='aluno')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='nps.pesquisa')),
                ('tratada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_tratadas', to=settings.AUTH_USER_MODEL, verbose_name='tratada por')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_de_pesquisa', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('pesquisa', 'aluno'), name='resposta_unica_por_aluno')],
            },
        ),
    ]
