# Generated by Django 5.2.6 on 2025-11-26 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painel',
            name='aula',
        ),
        migrations.AddField(
            model_name='painel',
            name='nome',
            field=models.CharField(default='Painel de Aulas', max_length=200, verbose_name='Nome do Painel'),
        ),
        migrations.CreateModel(
            name='PainelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aulas', verbose_name='Aula')),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='painel.painel')),
            ],
            options={
                'verbose_name': 'Item do Painel',
                'verbose_name_plural': 'Itens do Painel',
                'ordering': ['ordem'],
            },
        ),
    ]
