# Generated by Django 5.2.6 on 2025-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_remove_painel_aula_painel_nome_painelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='numero_de_user',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe em branco para sem limite', null=True, verbose_name='Capacidade de Alunos'),
        ),
    ]
