# Generated by Django 5.2.8 on 2026-09-13 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeDeAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato de adesao'), ('termo_de_saude', 'Termo de saude'), ('autorizacao_de_imagem', 'Autorizacao de imagem'), ('distrato', 'Distrato')], default='contrato', max_length=25, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('caminho_do_documento', models.CharField(blank=True, max_length=300, verbose_name='caminho do documento')),
                ('hash_do_documento', models.CharField(blank=True, max_length=64, verbose_name='hash do documento (sha256)')),
                ('situacao', models.CharField(choices=[('aguardando', 'Aguardando assinaturas'), ('parcial', 'Parcialmente assinado'), ('assinado', 'Assinado'), ('recusado', 'Recusado')], default='aguardando', max_length=12, verbose_name='situacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='concluido em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes', to='usuarios.usuario', verbose_name='aluno')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes_criados', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.rede')),
            ],
            options={
                'verbose_name': 'envelope de assinatura',
                'verbose_name_plural': 'envelopes de assinatura',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Signatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('papel', models.CharField(choices=[('aluno', 'Aluno'), ('responsavel', 'Responsavel legal'), ('academia', 'Representante da academia'), ('testemunha', 'Testemunha')], default='aluno', max_length=15, verbose_name='papel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('assinou', 'Assinou'), ('recusou', 'Recusou')], default='pendente', max_length=10, verbose_name='situacao')),
                ('assinou_em', models.DateTimeField(blank=True, null=True, verbose_name='assinou em')),
                ('motivo_da_recusa', models.CharField(blank=True, max_length=200, verbose_name='motivo da recusa')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatarios', to='documentos.envelopedeassinatura')),
            ],
            options={
                'verbose_name': 'signatario',
                'verbose_name_plural': 'signatarios',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='eletronica_simples', max_length=25, verbose_name='tipo')),
                ('hash_do_documento', models.CharField(max_length=64, verbose_name='hash do documento (sha256)')),
                ('hash_anterior', models.CharField(blank=True, max_length=64, verbose_name='hash do elo anterior')),
                ('hash_da_assinatura', models.CharField(max_length=64, verbose_name='hash desta assinatura')),
                ('endereco_ip', models.CharField(blank=True, max_length=45, verbose_name='endereco IP')),
                ('navegador', models.CharField(blank=True, max_length=200, verbose_name='navegador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('signatario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='documentos.signatario')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['criado_em'],
            },
        ),
    ]
