# Generated by Django 5.2.8 on 2026-09-13 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Para que este token serve', max_length=100, verbose_name='nome')),
                ('prefixo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='prefixo')),
                ('hash_segredo', models.CharField(editable=False, max_length=128, verbose_name='hash do segredo')),
                ('escopos', models.JSONField(default=list, verbose_name='escopos')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso em')),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ultimo IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('revogado_em', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_criados', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, help_text='Vazio = token vale para todas as unidades da rede', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.unidade')),
            ],
            options={
                'verbose_name': 'token de API',
                'verbose_name_plural': 'tokens de API',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('alterar', 'Alterar'), ('arquivar', 'Arquivar'), ('restaurar', 'Restaurar'), ('exportar', 'Exportar'), ('importar', 'Importar'), ('login', 'Entrar'), ('impersonar', 'Acesso de suporte'), ('api', 'Chamada de API')], max_length=20, verbose_name='acao')),
                ('entidade', models.CharField(max_length=80, verbose_name='entidade')),
                ('entidade_id', models.CharField(blank=True, max_length=64, verbose_name='id da entidade')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('dados_antes', models.JSONField(blank=True, null=True, verbose_name='antes')),
                ('dados_depois', models.JSONField(blank=True, null=True, verbose_name='depois')),
                ('pedido_origem', models.TextField(blank=True, verbose_name='pedido de origem')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='request id')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='core.rede')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='api.apitoken')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='core.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['rede', '-criado_em'], name='api_registr_rede_id_923389_idx'), models.Index(fields=['entidade', 'entidade_id'], name='api_registr_entidad_5c5426_idx')],
            },
        ),
    ]
