# Generated by Django 5.2.8 on 2026-09-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaAssincrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('relatorio', 'Relatorio'), ('importacao', 'Importacao'), ('exportacao', 'Exportacao'), ('lgpd', 'LGPD')], max_length=12, verbose_name='tipo')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='parametros')),
                ('situacao', models.CharField(choices=[('na_fila', 'Na fila'), ('rodando', 'Rodando'), ('concluida', 'Concluida'), ('falhou', 'Falhou')], default='na_fila', max_length=10, verbose_name='situacao')),
                ('progresso', models.PositiveSmallIntegerField(default=0, verbose_name='progresso (%)')),
                ('resultado', models.JSONField(blank=True, default=dict, verbose_name='resultado')),
                ('arquivo', models.CharField(blank=True, max_length=400, verbose_name='arquivo gerado')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('termina_em', models.DateTimeField(blank=True, null=True, verbose_name='link expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='core.rede', verbose_name='rede')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_pedidas', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='api.apitoken', verbose_name='token')),
            ],
            options={
                'verbose_name': 'tarefa assincrona',
                'verbose_name_plural': 'tarefas assincronas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='endereco')),
                ('eventos', models.JSONField(blank=True, default=list, help_text='Lista de eventos (RF-API-001). Vazio = todos.', verbose_name='eventos assinados')),
                ('segredo', models.CharField(max_length=80, verbose_name='segredo HMAC')),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado')], default='ativo', max_length=10, verbose_name='estado')),
                ('descricao', models.CharField(blank=True, max_length=160, verbose_name='descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rede', models.ForeignKey(blank=True, help_text='Em branco = webhook da plataforma.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.rede', verbose_name='rede')),
            ],
            options={
                'verbose_name': 'webhook de saida',
                'verbose_name_plural': 'webhooks de saida',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDeWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=60, verbose_name='evento')),
                ('entrega', models.CharField(max_length=40, unique=True, verbose_name='identificador da entrega')),
                ('payload', models.JSONField(default=dict, verbose_name='corpo enviado')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('falhou', 'Falhou'), ('desistiu', 'Desistiu')], default='pendente', max_length=10, verbose_name='situacao')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('resposta', models.CharField(blank=True, max_length=200, verbose_name='resposta')),
                ('proxima_tentativa', models.DateTimeField(blank=True, null=True, verbose_name='proxima tentativa')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='api.webhookdesaida', verbose_name='webhook')),
            ],
            options={
                'verbose_name': 'entrega de webhook',
                'verbose_name_plural': 'entregas de webhook',
                'ordering': ['-criado_em'],
            },
        ),
    ]
