# Generated by Django 5.2.8 on 2026-09-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRetencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=60, unique=True, verbose_name='entidade')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('prazo_dias', models.PositiveIntegerField(default=365, verbose_name='prazo (dias)')),
                ('base_legal', models.CharField(blank=True, max_length=200, verbose_name='base legal')),
                ('acao', models.CharField(choices=[('anonimizar', 'Anonimizar'), ('eliminar', 'Eliminar'), ('conservar', 'Conservar (base legal)')], default='anonimizar', max_length=20, verbose_name='acao')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'regra de retencao',
                'verbose_name_plural': 'regras de retencao',
                'ordering': ['entidade'],
            },
        ),
        migrations.CreateModel(
            name='AcessoDadoSensivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nome', models.CharField(max_length=150, verbose_name='titular')),
                ('usuario_id_titular', models.PositiveIntegerField(blank=True, null=True, verbose_name='id do cadastro')),
                ('recurso', models.CharField(default='ficha_saude', max_length=60, verbose_name='recurso')),
                ('acao', models.CharField(default='leitura', max_length=30, verbose_name='acao')),
                ('origem', models.CharField(choices=[('painel', 'Painel'), ('api', 'API'), ('suporte', 'Suporte'), ('impressao', 'Impressao/PDF')], default='painel', max_length=20, verbose_name='origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_sensiveis', to='core.rede', verbose_name='rede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_sensiveis', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'acesso a dado sensivel',
                'verbose_name_plural': 'acessos a dado sensivel',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_codigo', models.CharField(max_length=128, verbose_name='hash')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacao', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'codigo de recuperacao',
                'verbose_name_plural': 'codigos de recuperacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segredo', models.CharField(max_length=64, verbose_name='segredo')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dois_fatores', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'dispositivo 2FA',
                'verbose_name_plural': 'dispositivos 2FA',
            },
        ),
        migrations.CreateModel(
            name='ErroTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=200, verbose_name='rota')),
                ('metodo', models.CharField(blank=True, max_length=10, verbose_name='metodo')),
                ('status', models.PositiveSmallIntegerField(default=500, verbose_name='status HTTP')),
                ('tipo', models.CharField(blank=True, max_length=120, verbose_name='tipo')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('traceback_curto', models.TextField(blank=True, verbose_name='trecho do traceback')),
                ('resolvido', models.BooleanField(default=False, verbose_name='resolvido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros', to='core.rede', verbose_name='rede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_tenant', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'erro por cliente',
                'verbose_name_plural': 'erros por cliente',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=300, verbose_name='arquivo')),
                ('tipo', models.CharField(choices=[('banco', 'Banco de dados'), ('midia', 'Midia'), ('tenant', 'Exportacao de um cliente')], default='banco', max_length=20, verbose_name='tipo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='sha256')),
                ('situacao', models.CharField(choices=[('em_andamento', 'Em andamento'), ('ok', 'Concluido'), ('falhou', 'Falhou')], default='em_andamento', max_length=20, verbose_name='situacao')),
                ('verificado_em', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('verificacao', models.TextField(blank=True, verbose_name='resultado da verificacao')),
                ('retencao_ate', models.DateField(blank=True, null=True, verbose_name='reter ate')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.rede', verbose_name='rede')),
            ],
            options={
                'verbose_name': 'registro de backup',
                'verbose_name_plural': 'registros de backup',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_nome', models.CharField(max_length=150, verbose_name='titular')),
                ('titular_email', models.CharField(blank=True, max_length=200, verbose_name='e-mail do titular')),
                ('tipo', models.CharField(choices=[('acesso', 'Acesso aos dados'), ('exportacao', 'Exportacao'), ('correcao', 'Correcao'), ('eliminacao', 'Eliminacao/anonimizacao')], max_length=20, verbose_name='tipo')),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('concluida', 'Concluida'), ('recusada', 'Recusada')], default='aberta', max_length=20, verbose_name='situacao')),
                ('prazo_em', models.DateField(verbose_name='prazo legal')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta ao titular')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='concluida em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_titular', to='core.rede', verbose_name='rede')),
            ],
            options={
                'verbose_name': 'solicitacao de titular',
                'verbose_name_plural': 'solicitacoes de titular',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TentativaDeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=200, verbose_name='identificador')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('sucesso', models.BooleanField(default=False, verbose_name='sucesso')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['identificador', 'criado_em'], name='governanca__identif_081fd6_idx'), models.Index(fields=['ip', 'criado_em'], name='governanca__ip_43fc5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='hora')),
                ('requisicoes', models.PositiveIntegerField(default=0, verbose_name='requisicoes')),
                ('erros_5xx', models.PositiveIntegerField(default=0, verbose_name='erros 5xx')),
                ('erros_4xx', models.PositiveIntegerField(default=0, verbose_name='erros 4xx')),
                ('tempo_total_ms', models.BigIntegerField(default=0, verbose_name='tempo total (ms)')),
                ('tempo_max_ms', models.PositiveIntegerField(default=0, verbose_name='pior tempo (ms)')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metricas', to='core.rede', verbose_name='rede')),
            ],
            options={
                'verbose_name': 'metrica por cliente',
                'verbose_name_plural': 'metricas por cliente',
                'ordering': ['-inicio'],
                'constraints': [models.UniqueConstraint(fields=('rede', 'inicio'), name='metrica_unica_por_hora')],
            },
        ),
    ]
