# Generated by Django 5.2.8 on 2026-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('periodicidade', models.CharField(choices=[('hora', 'De hora em hora'), ('dia', 'Diaria'), ('semana', 'Semanal'), ('mes', 'Mensal')], default='dia', max_length=10, verbose_name='periodicidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('executa_dry_run', models.BooleanField(default=False, help_text='Roda a rotina sem gravar nada.', verbose_name='executa em modo simulacao')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='ultima execucao')),
                ('ultima_situacao', models.CharField(blank=True, choices=[('ok', 'Concluida'), ('falhou', 'Falhou'), ('pulada', 'Pulada')], max_length=10, verbose_name='situacao da ultima execucao')),
                ('ultimo_resultado', models.TextField(blank=True, verbose_name='resultado da ultima execucao')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='duracao (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'rotina agendada',
                'verbose_name_plural': 'rotinas agendadas',
                'ordering': ['nome'],
            },
        ),
    ]
