# Generated by Django 5.2.8 on 2026-09-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('pwa', 'Aplicativo do aluno'), ('totem', 'Totem da recepcao'), ('catraca', 'Catraca'), ('manual', 'Lancado pela equipe')], default='pwa', max_length=10, verbose_name='origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='usuarios.usuario', verbose_name='aluno')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.rede')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'check-in',
                'verbose_name_plural': 'check-ins',
                'ordering': ['-criado_em'],
            },
        ),
    ]
