# Generated by Django 5.2.8 on 2026-09-13 16:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('professores', '0005_professor_arquivado_em_professor_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuracaoDeComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='inicio do periodo')),
                ('fim', models.DateField(verbose_name='fim do periodo')),
                ('situacao', models.CharField(choices=[('previsto', 'Previsto'), ('emitido', 'Emitido'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='previsto', max_length=10, verbose_name='situacao')),
                ('base_de_calculo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='base de calculo')),
                ('valor_devido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor pago')),
                ('piso_aplicado', models.BooleanField(default=False, verbose_name='piso aplicado')),
                ('teto_aplicado', models.BooleanField(default=False, verbose_name='teto aplicado')),
                ('memoria', models.JSONField(blank=True, default=list, verbose_name='memoria de calculo')),
                ('hash_do_calculo', models.CharField(blank=True, max_length=64, verbose_name='hash do calculo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('emitido_em', models.DateTimeField(blank=True, null=True, verbose_name='emitido em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuracoes', to='professores.professor', verbose_name='professor')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuracoes', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuracoes', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'apuracao de comissao',
                'verbose_name_plural': 'apuracoes de comissao',
                'ordering': ['-inicio', 'professor__nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemDeComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('tipo', models.CharField(max_length=20, verbose_name='tipo')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='base')),
                ('percentual', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=6, verbose_name='percentual')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor')),
                ('apuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='remuneracao.apuracaodecomissao')),
            ],
            options={
                'verbose_name': 'item da comissao',
                'verbose_name_plural': 'itens da comissao',
                'ordering': ['apuracao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RegraDeComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('por_aula', 'Por aula dada'), ('por_aluno', 'Por aluno ativo'), ('percentual', 'Percentual do que a unidade recebeu'), ('fixo', 'Valor fixo no periodo')], max_length=12, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor por aula/aluno')),
                ('percentual', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=6, verbose_name='percentual')),
                ('piso_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='piso mensal')),
                ('teto_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='teto mensal')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='inicio da vigencia')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='fim da vigencia')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
                ('descricao', models.CharField(blank=True, max_length=160, verbose_name='descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(blank=True, help_text='Em branco = regra da unidade/rede.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_comissao', to='professores.professor', verbose_name='professor')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_comissao', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_comissao', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'regra de comissao',
                'verbose_name_plural': 'regras de comissao',
                'ordering': ['rede', 'unidade', 'professor', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='apuracaodecomissao',
            constraint=models.UniqueConstraint(fields=('professor', 'unidade', 'inicio', 'fim'), name='apuracao_unica_por_periodo'),
        ),
    ]
