# Generated by Django 5.2.8 on 2026-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regradecomissao',
            name='tipo',
            field=models.CharField(choices=[('por_aula', 'Por aula dada'), ('por_hora', 'Por hora trabalhada'), ('por_aluno', 'Por aluno ativo'), ('percentual', 'Percentual do que a unidade recebeu'), ('fixo', 'Valor fixo no periodo')], max_length=12, verbose_name='tipo'),
        ),
    ]
