# Generated by Django 5.2.8 on 2026-09-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('financeiro', '0006_despesa_arquivado_em_despesa_rede_despesa_unidade_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoDeDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('pix_automatico', 'Pix automatico'), ('cartao_recorrente', 'Cartao recorrente')], default='pix_automatico', max_length=20, verbose_name='modalidade')),
                ('chave_pix', models.CharField(blank=True, max_length=120, verbose_name='chave Pix do pagador')),
                ('limite_por_cobranca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='limite por cobranca')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente de confirmacao'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='pendente', max_length=12, verbose_name='situacao')),
                ('identificador_no_banco', models.CharField(blank=True, max_length=80, verbose_name='identificador no banco')),
                ('autorizada_em', models.DateTimeField(blank=True, null=True, verbose_name='autorizada em')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_de_debito', to='usuarios.usuario', verbose_name='aluno')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_de_debito', to='core.rede')),
            ],
            options={
                'verbose_name': 'autorizacao de debito',
                'verbose_name_plural': 'autorizacoes de debito',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='competencia (primeiro dia do mes)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('situacao', models.CharField(choices=[('prevista', 'Prevista'), ('enviada', 'Enviada ao banco'), ('paga', 'Paga'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='prevista', max_length=10, verbose_name='situacao')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas de envio')),
                ('motivo_da_recusa', models.CharField(blank=True, max_length=200, verbose_name='motivo da recusa')),
                ('identificador_no_banco', models.CharField(blank=True, max_length=80, verbose_name='identificador no banco')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='usuarios.usuario', verbose_name='aluno')),
                ('autorizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='cobranca.autorizacaodedebito')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='financeiro.pagamento')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='core.unidade')),
            ],
            options={
                'verbose_name': 'cobranca recorrente',
                'verbose_name_plural': 'cobrancas recorrentes',
                'ordering': ['vencimento', 'aluno__nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoDaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criada', 'Cobranca criada'), ('lembrete', 'Lembrete enviado ao aluno'), ('enviada', 'Enviada ao banco'), ('paga', 'Pagamento confirmado'), ('recusada', 'Recusada pelo banco'), ('devolvida', 'Devolvida ou estornada'), ('cancelada', 'Cancelada pela rede')], max_length=12, verbose_name='tipo')),
                ('detalhe', models.TextField(blank=True, verbose_name='detalhe')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados do retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cobranca.cobrancarecorrente')),
            ],
            options={
                'verbose_name': 'evento da cobranca',
                'verbose_name_plural': 'eventos da cobranca',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='autorizacaodedebito',
            constraint=models.UniqueConstraint(fields=('aluno', 'modalidade'), name='autorizacao_unica_por_aluno_e_modalidade'),
        ),
        migrations.AddIndex(
            model_name='cobrancarecorrente',
            index=models.Index(fields=['rede', 'situacao'], name='cobranca_co_rede_id_d8267c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cobrancarecorrente',
            constraint=models.UniqueConstraint(fields=('aluno', 'competencia'), name='cobranca_unica_por_aluno_e_competencia'),
        ),
    ]
