# Generated by Django 5.2.8 on 2026-09-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('financeiro', '0006_despesa_arquivado_em_despesa_rede_despesa_unidade_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('mei', 'MEI'), ('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=12, verbose_name='regime tributario')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='municipio')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=40, verbose_name='inscricao municipal')),
                ('codigo_do_servico', models.CharField(default='6.01', help_text='6.01 = educacao fisica, academia e esporte.', max_length=10, verbose_name='codigo do servico (LC 116)')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='aliquota de ISS (%)')),
                ('retem_pis_cofins_csll', models.BooleanField(default=False, verbose_name='reter PIS/COFINS/CSLL')),
                ('retem_ir', models.BooleanField(default=False, verbose_name='reter IR')),
                ('retem_inss', models.BooleanField(default=False, verbose_name='reter INSS')),
                ('provedor', models.CharField(choices=[('simulado', 'Simulado (sem emissao real)'), ('nacional', 'Emissor Nacional'), ('municipal', 'Emissor do municipio')], default='simulado', max_length=12, verbose_name='provedor de emissao')),
                ('ambiente', models.CharField(default='homologacao', max_length=12, verbose_name='ambiente')),
                ('token', models.CharField(blank=True, max_length=200, verbose_name='token do provedor')),
                ('emissao_automatica', models.BooleanField(default=False, verbose_name='emitir automaticamente ao receber')),
                ('serie', models.CharField(default='1', max_length=5, verbose_name='serie')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('rede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_fiscal', to='core.rede')),
            ],
            options={
                'verbose_name': 'configuracao fiscal',
                'verbose_name_plural': 'configuracoes fiscais',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='competencia')),
                ('descricao_do_servico', models.CharField(default='Mensalidade de atividade fisica', max_length=250, verbose_name='descricao do servico')),
                ('codigo_do_servico', models.CharField(default='6.01', max_length=10, verbose_name='codigo do servico')),
                ('valor_do_servico', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor do servico')),
                ('base_de_calculo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='base de calculo')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='aliquota de ISS (%)')),
                ('valor_do_iss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ISS')),
                ('retencoes', models.JSONField(blank=True, default=dict, verbose_name='retencoes')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor liquido')),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('erro', 'Erro na emissao')], default='pendente', max_length=10, verbose_name='situacao')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='numero da nota')),
                ('serie', models.CharField(blank=True, max_length=5, verbose_name='serie')),
                ('codigo_de_verificacao', models.CharField(blank=True, max_length=64, verbose_name='codigo de verificacao')),
                ('provedor', models.CharField(blank=True, max_length=12, verbose_name='provedor')),
                ('resposta_do_provedor', models.JSONField(blank=True, default=dict, verbose_name='resposta do provedor')),
                ('emitida_em', models.DateTimeField(blank=True, null=True, verbose_name='emitida em')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True, verbose_name='cancelada em')),
                ('motivo_do_cancelamento', models.CharField(blank=True, max_length=200, verbose_name='motivo do cancelamento')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='usuarios.usuario', verbose_name='tomador')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='financeiro.pagamento')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='core.unidade')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['-competencia', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='EventoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criada', 'Nota criada'), ('emitida', 'Emitida'), ('erro', 'Erro'), ('cancelada', 'Cancelada')], max_length=10, verbose_name='tipo')),
                ('detalhe', models.TextField(blank=True, verbose_name='detalhe')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='dados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'evento fiscal',
                'verbose_name_plural': 'eventos fiscais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['rede', 'situacao'], name='fiscal_nota_rede_id_f33b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('pagamento',), name='uma_nota_por_pagamento'),
        ),
    ]
