# Generated by Django 5.2.6 on 2025-11-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
