# Generated by Django 5.2.6 on 2025-12-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_bairro_user_alter_usuario_cep_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('restricoes', models.TextField(blank=True, null=True, verbose_name='Restrições')),
                ('prescricoes', models.TextField(blank=True, null=True, verbose_name='Prescrições')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usa_medicamento', models.BooleanField(default=False, verbose_name='Usa Medicamento?')),
                ('qual_medicamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual Medicamento?')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_saude', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Ficha de Saúde',
                'verbose_name_plural': 'Fichas de Saúde',
            },
        ),
    ]
