# Generated by Django 5.2.8 on 2026-09-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descricao')),
                ('evento', models.CharField(choices=[('checkin', 'Check-in na academia'), ('aula', 'Aula concluida'), ('avaliacao', 'Avaliacao fisica'), ('indicacao', 'Indicacao de amigo'), ('nps', 'Resposta de pesquisa'), ('pagamento_em_dia', 'Mes pago em dia')], max_length=20, verbose_name='evento')),
                ('quantidade', models.PositiveSmallIntegerField(default=10, verbose_name='quantidade necessaria')),
                ('pontos_bonus', models.PositiveIntegerField(default=0, verbose_name='pontos de bonus')),
                ('icone', models.CharField(blank=True, max_length=8, verbose_name='icone')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='core.rede')),
            ],
            options={
                'verbose_name': 'conquista',
                'verbose_name_plural': 'conquistas',
                'ordering': ['rede', 'evento', 'quantidade'],
            },
        ),
        migrations.CreateModel(
            name='SaldoDePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0, verbose_name='pontos')),
                ('nivel', models.PositiveSmallIntegerField(default=1, verbose_name='nivel')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_de_pontos', to='usuarios.usuario', verbose_name='aluno')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_de_pontos', to='core.rede')),
            ],
            options={
                'verbose_name': 'saldo de pontos',
                'verbose_name_plural': 'saldos de pontos',
                'ordering': ['-pontos'],
            },
        ),
        migrations.CreateModel(
            name='ConquistaDoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquistada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas_do_aluno', to='usuarios.usuario', verbose_name='aluno')),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganhadores', to='gamificacao.conquista')),
            ],
            options={
                'verbose_name': 'conquista do aluno',
                'verbose_name_plural': 'conquistas do aluno',
                'ordering': ['-conquistada_em'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'conquista'), name='conquista_unica_por_aluno')],
            },
        ),
        migrations.CreateModel(
            name='RegraDePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('checkin', 'Check-in na academia'), ('aula', 'Aula concluida'), ('avaliacao', 'Avaliacao fisica'), ('indicacao', 'Indicacao de amigo'), ('nps', 'Resposta de pesquisa'), ('pagamento_em_dia', 'Mes pago em dia')], max_length=20, verbose_name='evento')),
                ('pontos', models.PositiveIntegerField(default=10, verbose_name='pontos')),
                ('limite_diario', models.PositiveSmallIntegerField(default=1, help_text='0 = sem limite', verbose_name='limite por dia')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativa')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_pontos', to='core.rede')),
            ],
            options={
                'verbose_name': 'regra de pontos',
                'verbose_name_plural': 'regras de pontos',
                'ordering': ['rede', 'evento'],
                'constraints': [models.UniqueConstraint(fields=('rede', 'evento'), name='regra_de_pontos_unica')],
            },
        ),
        migrations.CreateModel(
            name='LancamentoDePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('checkin', 'Check-in na academia'), ('aula', 'Aula concluida'), ('avaliacao', 'Avaliacao fisica'), ('indicacao', 'Indicacao de amigo'), ('nps', 'Resposta de pesquisa'), ('pagamento_em_dia', 'Mes pago em dia')], max_length=20, verbose_name='evento')),
                ('pontos', models.IntegerField(verbose_name='pontos')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='gamificacao.saldodepontos')),
            ],
            options={
                'verbose_name': 'lancamento de pontos',
                'verbose_name_plural': 'lancamentos de pontos',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('saldo', 'evento', 'referencia'), name='lancamento_unico_por_referencia')],
            },
        ),
    ]
