# Generated by Django 5.2.6 on 2025-11-23 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco_prof', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero_end_prof', models.CharField(max_length=20, verbose_name='Número')),
                ('bairro_prof', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep_prof', models.CharField(max_length=20, verbose_name='CEP')),
                ('cpf_cnpj_prof', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('data_create_prof', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_at_prof', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('status_prof', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
