# Generated by Django 5.2.6 on 2025-11-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='foto_prof',
            field=models.ImageField(blank=True, null=True, upload_to='professores_fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
