# Generated by Django 5.2.6 on 2025-11-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_professor_foto_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email_prof',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone_prof',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
