# Generated by Django 5.2.8 on 2026-09-13 21:52

import core.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_professor_arquivado_em_professor_rede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto_prof',
            field=models.ImageField(blank=True, help_text='png, jpeg ou webp ate 5 MB. E a foto que o aluno ve ao escolher o professor.', null=True, upload_to='professores_fotos/', validators=[core.validadores.validar_imagem_de_capa], verbose_name='Foto de Perfil'),
        ),
    ]
