# Generated by Django 5.2.6 on 2025-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome do Site')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='IdentidadeVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotipo', models.ImageField(upload_to='logos/', verbose_name='Logotipo')),
                ('favicon', models.ImageField(upload_to='favicons/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Identidade Visual',
                'verbose_name_plural': 'Identidade Visual',
            },
        ),
    ]
