# Generated by Django 5.2.6 on 2025-11-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_alerta_vencimento',
            field=models.IntegerField(default=5, help_text='Quantidade de dias antes do vencimento para exibir alerta amarelo', verbose_name='Dias para Alerta de Vencimento'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='mensagem_aniversario',
            field=models.TextField(default='Parabéns pelo seu aniversário! Desejamos um dia maravilhoso e cheio de alegrias. A equipe {academia} te deseja muita saúde e felicidade!', help_text='Mensagem enviada por e-mail para aniversariantes. Use {academia} para o nome do site e {nome} para o nome da pessoa.', verbose_name='Mensagem de Aniversário'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='mensagem_pagamento_atrasado',
            field=models.TextField(default='Seu pagamento está em atraso. Por favor, regularize sua situação o quanto antes para continuar aproveitando nossos serviços.', help_text='Mensagem enviada por e-mail para usuários com pagamento atrasado', verbose_name='Mensagem de Pagamento Atrasado'),
        ),
    ]
