# Generated by Django 5.2.6 on 2025-12-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_configuracao_dias_alerta_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Tema Escuro'), ('light', 'Tema Claro')], default='dark', help_text='Escolha entre tema claro ou escuro para todo o sistema', max_length=10, verbose_name='Tema do Sistema'),
        ),
    ]
