# Generated by Django 5.2.8 on 2026-09-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('origem', models.CharField(choices=[('instagram', 'Instagram'), ('indicacao', 'Indicacao de aluno'), ('porta', 'Passou na porta'), ('site', 'Site ou landing'), ('whatsapp', 'WhatsApp'), ('google', 'Busca no Google'), ('parceiro', 'Parceiro ou empresa'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='origem')),
                ('interesse', models.CharField(blank=True, max_length=150, verbose_name='interesse')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor mensal estimado')),
                ('situacao', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('visita_agendada', 'Visita agendada'), ('visitou', 'Visitou'), ('matriculado', 'Matriculado'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='situacao')),
                ('motivo_da_perda', models.CharField(blank=True, max_length=200, verbose_name='motivo da perda')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('proximo_contato_em', models.DateField(blank=True, null=True, verbose_name='proximo contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('convertido_em', models.DateTimeField(blank=True, null=True, verbose_name='convertido em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_como_lead', to='usuarios.usuario', verbose_name='aluno gerado')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.rede')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.unidade')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoComLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligacao'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visita', 'Visita a unidade'), ('presencial', 'Atendimento presencial'), ('outro', 'Outro')], default='whatsapp', max_length=15, verbose_name='tipo')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('resultado', models.CharField(blank=True, max_length=200, verbose_name='resultado')),
                ('proximo_contato_em', models.DateField(blank=True, null=True, verbose_name='proximo contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('feito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_de_lead', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='relacionamento.lead')),
            ],
            options={
                'verbose_name': 'interacao com lead',
                'verbose_name_plural': 'interacoes com lead',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilDeRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.PositiveSmallIntegerField(default=0, verbose_name='pontuacao (0-100)')),
                ('faixa', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='baixo', max_length=10, verbose_name='faixa')),
                ('motivos', models.JSONField(blank=True, default=list, verbose_name='motivos')),
                ('dias_sem_treinar', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias sem treinar')),
                ('dias_em_atraso', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias em atraso')),
                ('detrator_recente', models.BooleanField(default=False, verbose_name='detrator recente')),
                ('total_de_checkins', models.PositiveIntegerField(default=0, verbose_name='check-ins registrados')),
                ('acao', models.CharField(choices=[('nenhuma', 'Nenhuma acao'), ('convite_avaliacao', 'Convidar para avaliacao fisica'), ('contato_whatsapp', 'Falar no WhatsApp'), ('ligacao', 'Ligar'), ('oferta_retencao', 'Oferta de retencao'), ('transferencia', 'Oferecer troca de unidade ou horario')], default='nenhuma', max_length=25, verbose_name='acao sugerida')),
                ('acao_definida_em', models.DateTimeField(blank=True, null=True, verbose_name='acao definida em')),
                ('desfecho', models.CharField(choices=[('em_aberto', 'Em aberto'), ('recuperado', 'Recuperado (voltou a treinar)'), ('continuou_ausente', 'Continuou ausente'), ('cancelou', 'Cancelou')], default='em_aberto', max_length=20, verbose_name='desfecho')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('calculado_em', models.DateTimeField(auto_now=True, verbose_name='calculado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_de_risco', to='usuarios.usuario', verbose_name='aluno')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_de_risco', to='core.rede')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_de_risco_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_de_risco', to='core.unidade')),
            ],
            options={
                'verbose_name': 'perfil de risco',
                'verbose_name_plural': 'perfis de risco',
                'ordering': ['-pontuacao', 'aluno__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['rede', 'situacao'], name='relacioname_rede_id_0a8681_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['rede', 'origem'], name='relacioname_rede_id_19be64_idx'),
        ),
        migrations.AddConstraint(
            model_name='perfilderisco',
            constraint=models.UniqueConstraint(fields=('aluno',), name='um_perfil_de_risco_por_aluno'),
        ),
    ]
