# Generated by Django 5.2.8 on 2026-09-13 14:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_conviteequipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emitente', models.CharField(default='SafeStack', max_length=120, verbose_name='nome do emitente')),
                ('cnpj_emitente', models.CharField(blank=True, max_length=20, verbose_name='CNPJ do emitente')),
                ('email_financeiro', models.EmailField(blank=True, max_length=254, verbose_name='e-mail financeiro')),
                ('asaas_api_key', models.CharField(blank=True, max_length=255, verbose_name='chave da API Asaas')),
                ('asaas_ambiente', models.CharField(choices=[('sandbox', 'Sandbox'), ('producao', 'Producao')], default='sandbox', max_length=10, verbose_name='ambiente Asaas')),
                ('asaas_base_url', models.CharField(blank=True, max_length=120, verbose_name='URL base da API')),
                ('token_webhook', models.CharField(blank=True, max_length=120, verbose_name='token do webhook')),
                ('trial_dias', models.PositiveSmallIntegerField(default=14, verbose_name='dias de teste')),
                ('dias_bloqueio', models.PositiveSmallIntegerField(default=10, verbose_name='dias para bloqueio de escrita')),
                ('dias_suspensao', models.PositiveSmallIntegerField(default=30, verbose_name='dias para suspensao')),
                ('multa_percentual', models.DecimalField(decimal_places=2, default=Decimal('2'), max_digits=5, verbose_name='multa (%)')),
                ('juros_dia_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.033'), max_digits=5, verbose_name='juros ao dia (%)')),
                ('regua_ativa', models.BooleanField(default=True, verbose_name='regua de cobranca ativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuracao da plataforma',
                'verbose_name_plural': 'configuracao da plataforma',
            },
        ),
        migrations.CreateModel(
            name='EventoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=20, verbose_name='gateway')),
                ('evento_id', models.CharField(max_length=120, unique=True, verbose_name='id do evento')),
                ('tipo', models.CharField(blank=True, max_length=60, verbose_name='tipo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('resultado', models.CharField(blank=True, max_length=120, verbose_name='resultado')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'evento de gateway',
                'verbose_name_plural': 'eventos de gateway',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='codigo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('limite_alunos', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de alunos')),
                ('limite_professores', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de professores')),
                ('limite_unidades', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de unidades')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='preco mensal')),
                ('preco_anual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='preco anual')),
                ('modulos', models.JSONField(blank=True, default=list, verbose_name='modulos habilitados')),
                ('ordem_exibicao', models.PositiveSmallIntegerField(default=0, verbose_name='ordem de exibicao')),
                ('visivel_no_site', models.BooleanField(default=True, verbose_name='visivel no site')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ['ordem_exibicao', 'preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10, verbose_name='ciclo')),
                ('inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='inicio')),
                ('renovacao_em', models.DateField(verbose_name='proxima renovacao')),
                ('trial_termina_em', models.DateField(blank=True, null=True, verbose_name='teste termina em')),
                ('cancelada_em', models.DateField(blank=True, null=True, verbose_name='cancelada em')),
                ('limite_alunos_custom', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de alunos (excecao)')),
                ('limite_professores_custom', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de professores (excecao)')),
                ('limite_unidades_custom', models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de unidades (excecao)')),
                ('motivo_excecao', models.TextField(blank=True, verbose_name='motivo da excecao')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='desconto (%)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excecoes_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='autorizado por')),
                ('rede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='core.rede', verbose_name='rede')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='plataforma.pacote', verbose_name='pacote')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['rede__nome'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=24, unique=True, verbose_name='numero')),
                ('periodo_inicio', models.DateField(verbose_name='periodo de')),
                ('periodo_fim', models.DateField(verbose_name='periodo ate')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='desconto')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor final')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('estornada', 'Estornada')], default='aberta', max_length=12, verbose_name='status')),
                ('pago_em', models.DateField(blank=True, null=True, verbose_name='pago em')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('cartao', 'Cartao')], max_length=10, verbose_name='forma')),
                ('gateway', models.CharField(blank=True, max_length=20, verbose_name='gateway')),
                ('gateway_id', models.CharField(blank=True, max_length=80, verbose_name='id no gateway')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR code (Pix)')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('link_pagamento', models.CharField(blank=True, max_length=255, verbose_name='link de pagamento')),
                ('observacao', models.TextField(blank=True, verbose_name='observacao')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturas', to='plataforma.assinatura', verbose_name='assinatura')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.rede', verbose_name='rede')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-vencimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Impersonacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_alvo', models.CharField(blank=True, max_length=150, verbose_name='usuario alvo')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='user agent')),
                ('acoes', models.PositiveIntegerField(default=0, verbose_name='acoes registradas')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonacoes', to='core.rede', verbose_name='rede')),
                ('usuario_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='usuario da plataforma')),
            ],
            options={
                'verbose_name': 'impersonacao',
                'verbose_name_plural': 'impersonacoes',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco', models.CharField(choices=[('T-7', 'Trial: faltam 7 dias'), ('T-3', 'Trial: faltam 3 dias'), ('T-1', 'Trial: ultimo dia'), ('D-3', 'Vencimento em 3 dias'), ('D0', 'Vence hoje'), ('D+1', '1 dia de atraso'), ('D+5', '5 dias: aviso de bloqueio'), ('D+10', '10 dias: bloqueio de escrita'), ('D+30', '30 dias: suspensao'), ('L80', 'Limite do pacote em 80%'), ('L95', 'Limite do pacote em 95%')], max_length=6, verbose_name='marco')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('painel', 'Painel')], default='email', max_length=10, verbose_name='canal')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha'), ('ignorado', 'Ignorado')], default='enviado', max_length=10, verbose_name='status')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_cobranca', to='core.rede', verbose_name='rede')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plataforma.fatura', verbose_name='fatura')),
            ],
            options={
                'verbose_name': 'evento de cobranca',
                'verbose_name_plural': 'eventos de cobranca',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('fatura', 'marco', 'canal'), name='unico_evento_por_marco')],
            },
        ),
    ]
