# Generated by Django 5.2.8 on 2026-09-13 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='juros_dia_percentual',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.033'), max_digits=6, verbose_name='juros ao dia (%)'),
        ),
    ]
