# Generated by Django 5.2.8 on 2026-09-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_configuracaoplataforma_juros_dia_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='pacote_agendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendadas', to='plataforma.pacote', verbose_name='pacote agendado'),
        ),
    ]
