# Generated by Django 5.2.8 on 2026-09-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_assinatura_pacote_agendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='limite_armazenamento_gb_custom',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='limite de armazenamento (GB, excecao)'),
        ),
        migrations.AddField(
            model_name='configuracaoplataforma',
            name='permitir_compra_de_pacote',
            field=models.BooleanField(default=False, help_text='Desligado por padrao: o cadastro nao oferece compra de pacote. Ligue aqui para habilitar a compra no cadastro e na troca de pacote.', verbose_name='permitir compra de pacote no cadastro'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='limite_armazenamento_gb',
            field=models.PositiveIntegerField(blank=True, help_text='Teto de video e imagem da rede. Em branco = sem teto.', null=True, verbose_name='limite de armazenamento (GB)'),
        ),
    ]
