# Generated by Django 5.2.8 on 2026-09-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialDeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cartao', 'Cartao de proximidade'), ('qr', 'QR do aplicativo'), ('biometria', 'Biometria'), ('manual', 'Lancada na recepcao')], default='cartao', max_length=10, verbose_name='tipo')),
                ('codigo', models.CharField(max_length=64, verbose_name='codigo')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('emitida_em', models.DateTimeField(auto_now_add=True, verbose_name='emitida em')),
                ('perdida_em', models.DateTimeField(blank=True, null=True, verbose_name='perdida ou cancelada em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais', to='usuarios.usuario', verbose_name='aluno')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais', to='core.rede')),
            ],
            options={
                'verbose_name': 'credencial de acesso',
                'verbose_name_plural': 'credenciais de acesso',
            },
        ),
        migrations.CreateModel(
            name='DispositivoDeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('catraca', 'Catraca'), ('portaria', 'Portaria'), ('totem', 'Totem'), ('aplicativo', 'Aplicativo do aluno')], default='catraca', max_length=12, verbose_name='tipo')),
                ('identificador', models.CharField(max_length=80, unique=True, verbose_name='identificador do equipamento')),
                ('token', models.CharField(max_length=64, verbose_name='token de integracao')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('ultima_comunicacao_em', models.DateTimeField(blank=True, null=True, verbose_name='ultima comunicacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_de_acesso', to='core.rede')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_de_acesso', to='core.unidade')),
            ],
            options={
                'verbose_name': 'dispositivo de acesso',
                'verbose_name_plural': 'dispositivos de acesso',
                'ordering': ['unidade__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDeParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.CharField(choices=[('wellhub', 'Wellhub (Gympass)'), ('totalpass', 'TotalPass'), ('classpass', 'ClassPass'), ('outro', 'Outro parceiro')], max_length=15, verbose_name='parceiro')),
                ('nome_no_parceiro', models.CharField(max_length=120, verbose_name='nome do plano no parceiro')),
                ('valor_por_acesso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor por acesso')),
                ('percentual_do_parceiro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual do parceiro (%)')),
                ('limite_de_acessos_por_mes', models.PositiveIntegerField(default=0, help_text='0 = sem limite', verbose_name='limite de acessos por mes')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_parceiro', to='core.rede')),
            ],
            options={
                'verbose_name': 'plano de parceiro',
                'verbose_name_plural': 'planos de parceiro',
            },
        ),
        migrations.CreateModel(
            name='ExtratoDeParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='competencia (primeiro dia do mes)')),
                ('nome_do_arquivo', models.CharField(blank=True, max_length=200, verbose_name='arquivo')),
                ('total_de_acessos', models.PositiveIntegerField(default=0, verbose_name='acessos no extrato')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor total do extrato')),
                ('situacao', models.CharField(choices=[('importado', 'Importado'), ('conciliado', 'Conciliado'), ('com_divergencia', 'Com divergencia')], default='importado', max_length=20, verbose_name='situacao')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True, verbose_name='conciliado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos_de_parceiro', to='core.rede')),
                ('plano_de_parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='acesso.planodeparceiro')),
            ],
            options={
                'verbose_name': 'extrato de parceiro',
                'verbose_name_plural': 'extratos de parceiro',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDeAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberado', models.BooleanField(default=False, verbose_name='liberado')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo da negativa')),
                ('origem', models.CharField(choices=[('catraca', 'Catraca'), ('portaria', 'Portaria'), ('totem', 'Totem'), ('aplicativo', 'Aplicativo do aluno'), ('manual', 'Lancada na recepcao')], default='catraca', max_length=12, verbose_name='origem')),
                ('codigo_apresentado', models.CharField(blank=True, max_length=64, verbose_name='codigo apresentado')),
                ('itinerante', models.BooleanField(default=False, verbose_name='entrou em unidade diferente da de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='usuarios.usuario', verbose_name='aluno')),
                ('credencial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='acesso.credencialdeacesso')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='acesso.dispositivodeacesso')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.rede')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.unidade')),
            ],
            options={
                'verbose_name': 'registro de acesso',
                'verbose_name_plural': 'registros de acesso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinhaDeExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('codigo', models.CharField(max_length=64, verbose_name='codigo do aluno no parceiro')),
                ('nome_informado', models.CharField(blank=True, max_length=150, verbose_name='nome informado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('conciliado', models.BooleanField(default=False, verbose_name='conciliado')),
                ('divergencia', models.CharField(blank=True, max_length=200, verbose_name='divergencia')),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='acesso.extratodeparceiro')),
                ('acesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linhas_de_extrato', to='acesso.registrodeacesso')),
            ],
            options={
                'verbose_name': 'linha de extrato',
                'verbose_name_plural': 'linhas de extrato',
                'ordering': ['data', 'codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='credencialdeacesso',
            constraint=models.UniqueConstraint(fields=('rede', 'codigo'), name='credencial_unica_por_rede'),
        ),
        migrations.AddConstraint(
            model_name='planodeparceiro',
            constraint=models.UniqueConstraint(fields=('rede', 'parceiro', 'nome_no_parceiro'), name='plano_de_parceiro_unico'),
        ),
        migrations.AddConstraint(
            model_name='extratodeparceiro',
            constraint=models.UniqueConstraint(fields=('plano_de_parceiro', 'competencia'), name='extrato_unico_por_competencia'),
        ),
        migrations.AddIndex(
            model_name='registrodeacesso',
            index=models.Index(fields=['rede', 'criado_em'], name='acesso_regi_rede_id_921a06_idx'),
        ),
        migrations.AddIndex(
            model_name='registrodeacesso',
            index=models.Index(fields=['rede', 'liberado'], name='acesso_regi_rede_id_5f15c2_idx'),
        ),
    ]
