# Generated by Django 5.2.8 on 2026-09-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0004_painel_arquivado_em_painel_rede_painel_unidade_and_more'),
        ('professores', '0005_professor_arquivado_em_professor_rede_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaDaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dor_ou_lesao', 'Dor ou lesao'), ('ausencia', 'Ausencia'), ('evolucao', 'Evolucao'), ('conduta', 'Conduta'), ('observacao', 'Observacao geral')], default='observacao', max_length=15, verbose_name='tipo')),
                ('descricao', models.TextField(verbose_name='descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='usuarios.usuario')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_registradas', to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='painel.painel')),
            ],
            options={
                'verbose_name': 'ocorrencia da turma',
                'verbose_name_plural': 'ocorrencias da turma',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SubstituicaoDeTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_como_substituto', to='professores.professor')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes_como_titular', to='professores.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicoes', to='painel.painel')),
            ],
            options={
                'verbose_name': 'substituicao de turma',
                'verbose_name_plural': 'substituicoes de turma',
                'ordering': ['-criado_em'],
            },
        ),
    ]
