# Generated by Django 5.2.8 on 2026-09-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0006_alter_aulas_file_de_video_alter_imagemaula_imagem'),
        ('core', '0004_conviteequipe_papeis'),
        ('painel', '0004_painel_arquivado_em_painel_rede_painel_unidade_and_more'),
        ('painel_do_professor', '0001_initial'),
        ('professores', '0006_alter_professor_foto_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeDoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em')),
                ('nome', models.CharField(default='Atendimento', help_text='O que o aluno ve ao escolher este horario (ex.: Atendimento individual).', max_length=120, verbose_name='nome do atendimento')),
                ('dia_da_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')], default=0, verbose_name='dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='abre as')),
                ('hora_fim', models.TimeField(verbose_name='fecha as')),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=60, help_text='A janela e dividida nesse tempo: cada parte vira um horario agendavel.', verbose_name='tempo do compromisso (minutos)')),
                ('vagas_por_horario', models.PositiveIntegerField(default=1, help_text='Quantos alunos cabem em cada horario.', verbose_name='vagas por horario')),
                ('inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='vale a partir de')),
                ('fim_vigencia', models.DateField(blank=True, null=True, verbose_name='vale ate')),
                ('ativo', models.BooleanField(default=True, verbose_name='aberta')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='professores.professor', verbose_name='professor')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'disponibilidade do professor',
                'verbose_name_plural': 'disponibilidades do professor',
                'ordering': ['dia_da_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AulaDaDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nas_disponibilidades', to='aulas.aulas')),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicao', to='painel_do_professor.disponibilidadedoprofessor')),
            ],
            options={
                'verbose_name': 'aula da disponibilidade',
                'verbose_name_plural': 'aulas da disponibilidade',
                'ordering': ['disponibilidade', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='TurmaMaterializada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('disponibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_geradas', to='painel_do_professor.disponibilidadedoprofessor')),
                ('turma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origem_da_agenda', to='painel.painel')),
            ],
            options={
                'verbose_name': 'turma materializada',
                'verbose_name_plural': 'turmas materializadas',
            },
        ),
        migrations.AddConstraint(
            model_name='disponibilidadedoprofessor',
            constraint=models.UniqueConstraint(fields=('professor', 'dia_da_semana', 'hora_inicio'), name='disponibilidade_unica_por_professor_dia_hora'),
        ),
        migrations.AddConstraint(
            model_name='auladadisponibilidade',
            constraint=models.UniqueConstraint(fields=('disponibilidade', 'aula'), name='aula_unica_por_disponibilidade'),
        ),
    ]
