# Generated by Django 5.2.8 on 2026-09-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conviteequipe_papeis'),
        ('painel_do_professor', '0002_disponibilidadedoprofessor_auladadisponibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auladadisponibilidade',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='auladadisponibilidade',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede'),
        ),
        migrations.AddField(
            model_name='auladadisponibilidade',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='turmamaterializada',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='turmamaterializada',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede'),
        ),
        migrations.AddField(
            model_name='turmamaterializada',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade'),
        ),
    ]
