# Generated by Django 5.2.8 on 2026-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conviteequipe_papeis'),
        ('painel_do_professor', '0003_auladadisponibilidade_arquivado_em_and_more'),
        ('professores', '0006_alter_professor_foto_prof'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disponibilidadedoprofessor',
            name='disponibilidade_unica_por_professor_dia_hora',
        ),
        migrations.AddConstraint(
            model_name='disponibilidadedoprofessor',
            constraint=models.UniqueConstraint(fields=('professor', 'dia_da_semana', 'hora_inicio', 'unidade'), name='disponibilidade_unica_por_professor_dia_hora'),
        ),
    ]
