server {
    listen 80;
    server_name academia.safestack.com.br localhost;
    client_max_body_size 25m;

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /app/media/;
        expires 7d;
        access_log off;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass web:8000;
        uwsgi_read_timeout 120;
    }
}
