# Generated by Django 5.2.6 on 2025-11-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='PagBank', editable=False, max_length=50)),
                ('ativo', models.BooleanField(default=True, verbose_name='Gateway Ativo')),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox (Testes)'), ('producao', 'Produção')], default='sandbox', max_length=20, verbose_name='Ambiente')),
                ('token', models.CharField(max_length=255, verbose_name='Token de Acesso')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='Chave Pública (Public Key)')),
                ('url_webhook', models.URLField(blank=True, help_text='URL para receber atualizações de status', null=True, verbose_name='URL de Notificação (Webhook)')),
            ],
            options={
                'verbose_name': 'Configuração do Gateway (PagBank)',
                'verbose_name_plural': 'Configuração do Gateway (PagBank)',
            },
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_pagamento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='pagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code (Pix)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code_text',
            field=models.TextField(blank=True, null=True, verbose_name='Código Pix (Copia e Cola)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('em_analise', 'Em Análise'), ('devolvido', 'Devolvido')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Transação (Gateway)'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
