# Generated by Django 5.2.8 on 2025-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_gatewayconfig_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewayconfig',
            options={'verbose_name': 'Configuração do Gateway de Pagamento', 'verbose_name_plural': 'Configuração do Gateway de Pagamento'},
        ),
        migrations.RemoveField(
            model_name='gatewayconfig',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='gatewayconfig',
            name='token',
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='access_token',
            field=models.CharField(default='', help_text='Token de acesso do gateway', max_length=255, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('pagbank', 'PagBank')], default='mercadopago', max_length=20, verbose_name='Gateway de Pagamento'),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='public_key',
            field=models.CharField(blank=True, default='', help_text='Chave pública para checkout', max_length=255, verbose_name='Public Key'),
        ),
    ]
