# Generated by Django 5.2.8 on 2025-12-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_gatewayconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagem de Capa'),
        ),
    ]
