# Generated by Django 5.2.8 on 2026-09-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_despesa_arquivado_em_despesa_rede_despesa_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('pagbank', 'PagBank'), ('asaas', 'Asaas')], default='mercadopago', max_length=20, verbose_name='Gateway de Pagamento'),
        ),
    ]
