# Generated by Django 5.2.8 on 2026-09-14 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_conviteequipe_papeis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoDaRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em')),
                ('provedor', models.CharField(db_index=True, max_length=40, verbose_name='provedor')),
                ('ativo', models.BooleanField(default=False, verbose_name='ativa')),
                ('campos', models.JSONField(blank=True, default=dict, verbose_name='valores recebidos')),
                ('arquivo', models.FileField(blank=True, help_text='Certificado ou arquivo que o provedor entrega (o nome fica junto dos valores).', upload_to='integracoes/', verbose_name='arquivo enviado')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('atualizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='atualizada por')),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'Integracao da rede',
                'verbose_name_plural': 'Integracoes da rede',
                'ordering': ('provedor',),
                'constraints': [models.UniqueConstraint(fields=('rede', 'provedor'), name='integracao_unica_por_rede')],
            },
        ),
    ]
