# Generated by Django 5.2.8 on 2026-09-13 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('codigo', models.CharField(blank=True, max_length=60, verbose_name='codigo ou codigo de barras')),
                ('preco_de_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preco de venda')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='estoque atual')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='estoque minimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.unidade')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=12, verbose_name='situacao')),
                ('forma_de_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Cartao de credito'), ('debito', 'Cartao de debito'), ('fiado', 'A prazo (fiado)')], max_length=10, verbose_name='forma de pagamento')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observacoes')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='usuarios.usuario', verbose_name='cliente')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_abertas', to=settings.AUTH_USER_MODEL)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='core.unidade')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoDeEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida por venda'), ('ajuste', 'Ajuste de inventario'), ('devolucao', 'Devolucao de venda')], max_length=10, verbose_name='tipo')),
                ('quantidade', models.IntegerField(verbose_name='quantidade (positiva entrada, negativa saida)')),
                ('saldo_apos', models.IntegerField(default=0, verbose_name='saldo apos o movimento')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_de_estoque', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='pdv.produto')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='pdv.venda')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preco unitario (no momento da venda)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_venda', to='pdv.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pdv.venda')),
            ],
            options={
                'verbose_name': 'item da venda',
                'verbose_name_plural': 'itens da venda',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('rede', 'nome'), name='produto_unico_por_rede'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['rede', 'situacao'], name='pdv_venda_rede_id_09fc2a_idx'),
        ),
    ]
