# Generated by Django 5.2.6 on 2025-11-23 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Aula')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('file_de_video', models.FileField(blank=True, null=True, upload_to='videos_aulas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Arquivo de Vídeo')),
                ('categorias_exercicios', models.CharField(choices=[('aerobico', 'Aeróbico/Cardiovascular'), ('forca', 'Treinamento de Força'), ('flexibilidade', 'Flexibilidade/Alongamento'), ('neuromotor', 'Equilíbrio e Coordenação'), ('pilates_solo', 'Pilates Solo (Mat)'), ('pilates_aparelhos', 'Pilates em Aparelhos')], max_length=50, verbose_name='Categoria')),
                ('data_create_aula', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_at_aula', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor/Criador')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='ImagemAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_aulas/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='aulas.aulas')),
            ],
        ),
    ]
