# Generated by Django 5.2.6 on 2025-11-29 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='file_de_video',
            field=models.FileField(blank=True, null=True, upload_to='videos_aulas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mkv'])], verbose_name='Arquivo de Vídeo'),
        ),
    ]
