# Generated by Django 5.2.6 on 2025-12-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_alter_aulas_file_de_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='restricao',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('cardiaco', 'Problemas Cardíacos'), ('respiratorio', 'Problemas Respiratórios'), ('coluna', 'Problemas de Coluna'), ('articulacao', 'Problemas Articulares'), ('gestante', 'Gestante'), ('hipertensao', 'Hipertensão'), ('lesao_muscular', 'Lesão Muscular'), ('diabetes', 'Diabetes'), ('obesidade', 'Obesidade')], default='nenhuma', max_length=50, verbose_name='Restrição de Saúde'),
        ),
    ]
