# Generated by Django 5.2.8 on 2026-09-13 21:52

import core.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_aulas_arquivado_em_aulas_rede_aulas_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='file_de_video',
            field=models.FileField(blank=True, help_text='Video de atividade de ate 450 MB (mp4, webm, ogg, mkv, mov ou avi). Para arquivo grande, use o envio em partes do painel de midia.', null=True, upload_to='videos_aulas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mkv', 'mov', 'avi']), core.validadores.validar_video_de_aula], verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AlterField(
            model_name='imagemaula',
            name='imagem',
            field=models.ImageField(help_text='Capa da aula: png, jpeg ou webp ate 5 MB.', upload_to='imagens_aulas/', validators=[core.validadores.validar_imagem_de_capa]),
        ),
    ]
