# Generated by Django 5.2.6 on 2025-11-29 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='Servidor SMTP (Host)')),
                ('port', models.IntegerField(default=587, verbose_name='Porta')),
                ('username', models.CharField(max_length=255, verbose_name='Usuário/Email')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('remetente_nome', models.CharField(default='Academia System', max_length=255, verbose_name='Nome do Remetente')),
                ('remetente_email', models.EmailField(max_length=254, verbose_name='Email do Remetente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configuração de E-mail',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('destinatarios', models.TextField(help_text='Emails separados por vírgula', verbose_name='Destinatários (separados por vírgula)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falha', 'Falha')], default='pendente', max_length=20, verbose_name='Status')),
                ('erro_log', models.TextField(blank=True, verbose_name='Log de Erro')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
