# Generated by Django 5.2.6 on 2025-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500, verbose_name='Access Token')),
                ('phone_number_id', models.CharField(max_length=100, verbose_name='Phone Number ID')),
                ('business_account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Business Account ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
            ],
            options={
                'verbose_name': 'Configuração de WhatsApp',
                'verbose_name_plural': 'Configuração de WhatsApp',
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='destinatarios',
            field=models.TextField(help_text='Emails ou números separados por vírgula', verbose_name='Destinatários'),
        ),
    ]
