# Generated by Django 5.2.8 on 2026-09-13 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('notificacoes', '0002_configuracaowhatsapp_notificacao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemail',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede'),
        ),
        migrations.AddField(
            model_name='configuracaoemail',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede'),
        ),
        migrations.AddField(
            model_name='configuracaowhatsapp',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='arquivado em'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.rede', verbose_name='rede'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='core.unidade', verbose_name='unidade'),
        ),
    ]
