# Generated by Django 5.2.8 on 2026-09-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0005_aulas_arquivado_em_aulas_rede_aulas_unidade_and_more'),
        ('core', '0003_rede_certificado_emitido_em_rede_certificado_erro_and_more'),
        ('professores', '0005_professor_arquivado_em_professor_rede_and_more'),
        ('usuarios', '0006_fichasaude_arquivado_em_fichasaude_rede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioDoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='exercicio')),
                ('series', models.PositiveSmallIntegerField(default=3, verbose_name='series')),
                ('repeticoes', models.CharField(default='12', max_length=30, verbose_name='repeticoes')),
                ('carga_sugerida', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='carga sugerida (kg)')),
                ('descanso_segundos', models.PositiveSmallIntegerField(default=60, verbose_name='descanso (s)')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observacoes')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios_prescritos', to='aulas.aulas', verbose_name='videoaula')),
            ],
            options={
                'verbose_name': 'exercicio do treino',
                'verbose_name_plural': 'exercicios do treino',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoDoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('carga', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='carga (kg)')),
                ('repeticoes', models.CharField(blank=True, max_length=30, verbose_name='repeticoes feitas')),
                ('esforco_percebido', models.PositiveSmallIntegerField(default=0, verbose_name='esforco percebido (1-10)')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observacoes')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='treinos.exerciciodotreino')),
            ],
            options={
                'verbose_name': 'execucao do exercicio',
                'verbose_name_plural': 'execucoes do exercicio',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('objetivo', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('condicionamento', 'Condicionamento'), ('forca', 'Forca'), ('reabilitacao', 'Reabilitacao'), ('mobilidade', 'Mobilidade')], default='condicionamento', max_length=20, verbose_name='objetivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='inicio')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('situacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=10, verbose_name='situacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='usuarios.usuario', verbose_name='aluno')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinos', to='professores.professor', verbose_name='professor')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinos', to='core.unidade')),
            ],
            options={
                'verbose_name': 'treino',
                'verbose_name_plural': 'treinos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='exerciciodotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treino'),
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='altura (m)')),
                ('percentual_de_gordura', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='percentual de gordura (%)')),
                ('massa_muscular', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='massa muscular (kg)')),
                ('medidas', models.JSONField(blank=True, default=dict, verbose_name='medidas (cm)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fisicas', to='usuarios.usuario', verbose_name='aluno')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_realizadas', to='professores.professor', verbose_name='avaliador')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fisicas', to='core.rede')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_fisicas', to='core.unidade')),
            ],
            options={
                'verbose_name': 'avaliacao fisica',
                'verbose_name_plural': 'avaliacoes fisicas',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'data'), name='uma_avaliacao_por_dia')],
            },
        ),
        migrations.AddIndex(
            model_name='treino',
            index=models.Index(fields=['rede', 'situacao'], name='treinos_tre_rede_id_0dc306_idx'),
        ),
    ]
